version: "3"

tasks:
  #
  # sdk
  #
  sdk:build:
    dir: sdk
    deps:
      - task: yarn:install
        vars:
          PROJECT_DIR: sdk
    cmds:
      - yarn build

  sdk:test:
    dir: sdk
    cmds:
      - yarn test

  sdk:publish:
    dir: sdk
    cmds:
      - echo "todo {{ .TASK }}"

  #
  # express
  #
  express:build:
    desc: Build the Extress middleware
    dir: frameworks/express
    deps:
      - task: yarn:install
        vars:
          PROJECT_DIR: frameworks/express
    cmds:
      - yarn build

  express:test:
    dir: frameworks/express
    cmds:
      - yarn test

  express:publish:
    dir: frameworks/express
    cmds:
      - echo "todo {{ .TASK }}"
  #
  # hapi
  #
  hapi:build:
    desc: Build the Extress middleware
    dir: frameworks/hapi
    deps:
      - task: yarn:install
        vars:
          PROJECT_DIR: frameworks/hapi
    cmds:
      - yarn build

  hapi:test:
    dir: frameworks/hapi
    cmds:
      - yarn test

  hapi:publish:
    dir: frameworks/hapi
    cmds:
      - echo "todo {{ .TASK }}"

  #
  # utility stuff
  #
  yarn:install:
    dir: "{{.PROJECT_DIR}}"
    cmds:
      - yarn install {{.CLI_ARGS}}

  #
  # composite tasks
  #
  build-all:
    - task: sdk:build
    - task: express:build
    - task: hapi:build

  test-all:
    deps: [build-all]
    cmds:
      - task: sdk:test
      - task: express:test
      - task: hapi:test

  publish-all:
    deps: [build-all]
    cmds:
      - task: sdk:publish
      - task: express:publish
      - task: hapi:publish
