version: "3"

tasks:
  #
  # sdk
  #
  sdk:build:
    dir: sdk
    deps:
      - task: yarn:install
    cmds:
      - yarn build

  sdk:test:
    dir: sdk
    cmds:
      - yarn test

  sdk:publish:
    desc: Publish @useoptic/optic-node-sdk
    dir: sdk
    cmds:
      - task: yarn:publish:guard
        vars:
          PROJECT_DIR: sdk

  #
  # express
  #
  express:build:
    desc: Build the Extress middleware
    dir: frameworks/express
    deps:
      - task: sdk:build
    cmds:
      - yarn build

  express:test:
    dir: frameworks/express
    cmds:
      - yarn test

  express:publish:
    desc: Publish @useoptic/express-middleware
    dir: frameworks/express
    cmds:
      - task: yarn:publish:guard
        vars:
          PROJECT_DIR: frameworks/express

  #
  # hapi
  #
  hapi:build:
    desc: Build the Extress middleware
    dir: frameworks/hapi
    deps:
      - sdk:build
    cmds:
      - yarn build

  hapi:test:
    dir: frameworks/hapi
    cmds:
      - yarn test

  hapi:publish:
    desc: Publish @useoptic/hapi-middleware
    dir: frameworks/hapi
    cmds:
      - task: yarn:publish:guard
        vars:
          PROJECT_DIR: frameworks/hapi

  #
  # utility stuff
  #
  yarn:install:
    cmds:
      - yarn install {{.CLI_ARGS}}

  yarn:publish:
    dir: "{{.PROJECT_DIR}}"
    env:
      NPM_AUTH_TOKEN: "{{.NPM_AUTH_TOKEN}}"
    cmds:
      - yarn publish --access=public --non-interactive
    preconditions:
      - sh: "[[ -n $NPM_AUTH_TOKEN ]]"
        msg: "You must set NPM_AUTH_TOKEN"

  yarn:publish:guard:
    dir: "{{.PROJECT_DIR}}"
    silent: true
    env:
      DRY_RUN: '{{default "true" .DRY_RUN}}'
    cmds:
      - |
        if [ $DRY_RUN = true ]
        then
          echo "This will publish $(cat package.json | jq -r '. | .name + "@" + .version'). Set DRY_RUN=false to proceed."
          exit 1
        fi
      - task: yarn:publish
        vars:
          PROJECT_DIR: "{{.PROJECT_DIR}}"

  #
  # composite tasks
  #
  build-all:
    - task: sdk:build
    - task: express:build
    - task: hapi:build

  test-all:
    deps: [build-all]
    cmds:
      - task: sdk:test
      - task: express:test
      - task: hapi:test

  publish-all:
    deps: [build-all]
    cmds:
      - task: sdk:publish
      - task: express:publish
      - task: hapi:publish
