name: Publish @useoptic/express-middleware

on:
  create:
  push:

jobs:
  publish:
    # if: ${{ startsWith(github.ref, 'refs/tags/express/v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # v2.3.3
      - name: Install Task
        run: curl -sL https://taskfile.dev/install.sh | sudo bash -s -- -b /usr/local/bin/
      - uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea # v2.1.5
        with:
          node-version: 14.16.0
      - run: task express:build
        env:
          NPM_AUTH_TOKEN: ${{ secrets.PUBLISH_NPM_OPTIC_BOT }}
